"""Writes row-images.js: the photos each gallery row shows, read from its
category folder in images/ (one folder per row, top to bottom).

Run from the project folder after adding, removing or renaming photos in
those folders:

    python3 tools/make-row-images.py

Then run tools/make-intro-images.py too, so the opening intro has tiny
copies of the same photos. A row shows its folder's photos in file-name
order.
"""
import json
import os
import unicodedata

# Same order as ROW_TITLES in sketch.js.
ROW_FOLDERS = ["Politik", "Veranstaltungen", "Wirtschaft", "Porträt", "Personal_Projects"]
EXTENSIONS = {".jpg", ".jpeg", ".png", ".webp"}
TARGET = "row-images.js"


def nfc(name):
    # macOS hands out decomposed umlauts ("a" + combining dots); the site
    # asks the server for the composed ones.
    return unicodedata.normalize("NFC", name)


def main():
    rows = []
    for folder in ROW_FOLDERS:
        path = os.path.join("images", folder)
        files = sorted(
            nfc(f) for f in os.listdir(path)
            if not f.startswith(".") and os.path.splitext(f)[1].lower() in EXTENSIONS
        )
        if not files:
            raise SystemExit(f"No photos in {path}")
        rows.append([f"{nfc(folder)}/{f}" for f in files])

    lines = [
        "// Generated by tools/make-row-images.py from the category folders in",
        "// images/ — edit the folders and rerun it rather than editing this file.",
        "// One list per gallery row, top to bottom (same order as ROW_TITLES in",
        "// sketch.js); paths are relative to images/.",
        "const ROW_IMAGE_FILES = [",
    ]
    for folder, files in zip(ROW_FOLDERS, rows):
        lines.append(f"  // {nfc(folder)}")
        lines.append("  [")
        lines.extend(f"    {json.dumps(f, ensure_ascii=False)}," for f in files)
        lines.append("  ],")
    lines.append("];")

    with open(TARGET, "w", encoding="utf-8") as out:
        out.write("\n".join(lines) + "\n")
    print(f"{TARGET}: " + ", ".join(f"{folder} {len(files)}" for folder, files in zip(ROW_FOLDERS, rows)))


if __name__ == "__main__":
    main()
